[project]
name = "2_1D_Gauge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.30.1",
    "jax==0.6.2",
    "matplotlib>=3.10.5",
    "memory-profiler>=0.61.0",
    "netket>=3.16.1.post1",
]
